### PR TITLE
constraints: option to include global upper capacity limit

### PR DESCRIPTION
**Pull request by martacki**
# Closes # (if applicable).

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [x] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by pz-max** [comment]
Nice!
- editing the release notes and
- adding a brief documentation
would be nice :)

**Comment by martacki** [comment]
Done @pz-max :) (you were too impacient ;) )

**Review by pz-max — APPROVED** [review]
Sweet :1st_place_medal:

**Comment by pz-max** [comment]
In future, we should add tests also for the wildcards optins. But let's do that after Merge March 2024.

**Pull request merged**
